CREATE DATABASE IF NOT EXISTS cadastros;
USE cadastros;

CREATE TABLE pessoas (NOME VARCHAR(100), IDADE VARCHAR(3), ALTURA_CM VARCHAR(3), PESO_KG VARCHAR(3));
INSERT INTO pessoas VALUES ("Luiz Henrique", "25", "175", "95");